[target.x86_64-unknown-linux-gnu]
image = "quininer/cross-nk:x86_64-unknown-linux-gnu-0.0.3"
runner = "qemu-system"

[target.aarch64-unknown-linux-gnu]
image = "quininer/cross-nk:aarch64-unknown-linux-gnu-0.0.2"
runner = "qemu-system"
